In [1]:
import numpy as np

In [ ]:
a = np.random.uniform(size=(100,100))
b = a[:2,:2]
b[0,0] = 99
print(a[:2,:2])

In [2]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
b = a.reshape((3,4))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
b[0,0] = 99

In [5]:
print(a)

[99  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
print(b)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
import numpy as np
a = np.arange(12)
b = a.reshape((3,4))
b.shape = (12,)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
import numpy as np

In [8]:
a = np.arange(12)

In [9]:
b = a.reshape((3,4))

In [10]:
c = b.T
print(c)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [11]:
import numpy as np
a = np.arange(12)
b = a.reshape((3,4))
b.shape = (12,)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
import numpy as np
a = np.arange(12)
b = a.reshape((3,4))
c = b.T
c.shape = (12,)
print(a)
print(c)

AttributeError: incompatible shape for a non-contiguous array

In [13]:
import numpy as np
a = np.arange(12)
b = a.reshape((3,4))
c = b.T
c[0,0] = 99
print(a)
print(c)

[99  1  2  3  4  5  6  7  8  9 10 11]
[[99  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [9]:
import numpy as np
a = np.arange(12)
b = a.reshape((3,4))
c = b.T
c = c.reshape((12,))
print(a)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [10]:
import numpy as np
a = np.arange(12)
b = a.reshape((3,4))
c = b.T
c = c.reshape((12,)) # copy
c[0] = 99
print(a)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[99  4  8  1  5  9  2  6 10  3  7 11]
